accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


app_name = 'accounts'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

web_fingerprint_authn/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import mfa
import mfa.TrustedDevice

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mfa/', include('mfa.urls')), #required to use mfa
    path('devices/add/', 
         mfa.TrustedDevice.add,
         name="mfa_add_new_trusted_device"), #required if you intend adding some devices
    path("", include('accounts.urls',
                     namespace='accounts')), #include accounts with namespace
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    display_name = models.CharField(max_length=32)

accounts/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib import auth
from django.utils import timezone
from django.conf import settings
from .models import User
from . import utils

# Create your views here.
def register(request):
    if request.method == "POST":
        error = ''
        username = request.POST.get('username')
        display_name = request.POST.get('display-name')
        if not utils.validate_username(username):
           error = 'Invalid User name'
           return render(request, 'register.html',
                         context = {'page_title': "Register", 'error': error})
        if not utils.validate_display_name(display_name):
           error = 'Invalid display name'
           return render(request, 'register.html',
                         context = {'page_title': "Register", 'error': error})
        if User.objects.filter(username=username).exists():
            error = 'user already exists.'
            return render(request, 'register.html',
                          context = {'page_title': "Register", 'error': error})
        else:
            u = User.objects.create(first_name = display_name,
                                    password='none', is_superuser=False,
                                    username=username,  last_name='last_name',
                                    display_name=display_name, email='email',
                                    is_staff=False, is_active=True,date_joined=timezone.now())
            u.backend = 'django.contrib.auth.backends.ModelBackend'
            auth.login(request,u)
            return redirect(reverse('start_fido2'))
    else:
        return render(request, 'register.html', context = {'page_title': "Register"})
    
def login_user_in(request, username):
    user=User.objects.get(username=username)
    user.backend='django.contrib.auth.backends.ModelBackend'
    auth.login(request, user)
    if "redirect" in request.POST:
        return redirect(request.POST["redirect"])
    else:
        return redirect(reverse('accounts:index'))

def login(request):
    if request.method == "POST":
        username = request.POST.get('username').replace('/', '')
        user = User.objects.filter(username=username).first()
        err=""
        if user is not None:
            if user.is_active:
                if "mfa" in settings.INSTALLED_APPS:
                    from mfa.helpers import has_mfa
                    res =  has_mfa(request,username=username)
                    if res: return res
                    return login_user_in(request, username)
            else:
                err="This User is NOT activated yet."
        else:
            err="No User with such username exists."
        return render(request, 'login.html', {"err":err})
    else:
        return render(request, 'login.html')



def index(request):
    return render(request, 'index.html', {"page_title": "Welcome home"})

accounts/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description" content="" />
    <meta name="author" content="Moses, Ifeanyichukwu" />
    <meta name="generator" content="Hugo 0.82.0" />
    <title>Web fingerprint authentication | {% block title %} {% endblock title %}</title>

    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link
      href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap"
      rel="stylesheet"
    />

    <!-- Bootstrap core CSS -->
    <link
      href="{% static 'css/bootstrap/css/bootstrap.min.css' %}"
      rel="stylesheet"
    />

    <script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
    <!-- <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script> -->
    {% block head %} {% endblock %} {% block css %} {% endblock css %}
  </head>

  {% block content %} {% endblock content %}
</html>

accounts/templates/index.html
{% extends 'base.html' %}
<!-- load static -->
{% load static %}
<!-- title -->
{% block title %} {{page_title}} {% endblock title %}
<!-- css -->
{% block css %}
<link rel="stylesheet" href="{% static 'css/custom.css' %}" />
{% endblock css %}
<!-- content -->
{% block content %}
<body class="d-flex h-100 text-center text-white bg-dark">
  <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
    <header class="mb-auto">
      <div>
        <h3 class="float-md-start mb-0">Fingerprint</h3>
        <nav class="nav nav-masthead justify-content-center float-md-end">
          <a
            class="nav-link active"
            aria-current="page"
            href="{% url 'accounts:index' %}"
            >Home</a
          >

          {% if request.user.is_authenticated %}
          <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
          {% else %}
          <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
          <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
          {% endif %}
        </nav>
      </div>
    </header>

    <main class="px-3">
      {% if request.user.is_authenticated %}

      <h1>You are logged in!!!!</h1>
      <p class="lead">Login succesful...</p>
      <p class="lead">
        <a
          href="https://github.com/mkalioby/django-mfa2"
          class="btn btn-lg btn-secondary fw-bold border-white bg-white"
          >Learn more</a
        >
      </p>
      {% else %}

      <h1>Fingerprint authentication on a practical web.</h1>
      <p class="lead">
        This project is a simulation of Fingerprint authentication on a website
        which can be practically be applied to any web based application that
        uses password to login user and intend to change to fingerprint authentication.
      </p>
      <p class="lead">
        <a
          href="https://nimc.gov.ng/about-us/"
          class="btn btn-lg btn-secondary fw-bold border-white bg-white"
          >Learn more</a
        >
      </p>

      <section>
        <div>
          NIMC operates and regulates matters of national identity in Nigeria
          with services covering National Identification Number (NIN) enrolment
          and issuance, National e-ID card issuance, identity verification as
          well as data harmonization and authentication. The Commission is
          headed by Engr. Aliyu A. Aziz who was a pioneer staff…
          <a
            href="https://nimc.gov.ng/engr-aliyu-a-aziz/"
            class="text-white bg-black"
            >Read more</a
          >
        </div>
      </section>
      {% endif %}
    </main>

    <footer class="mt-auto text-white-50">
      <p>
        Cover template for
        <a href="https://getbootstrap.com/" class="text-white">Bootstrap</a>, by
        <a href="https://twitter.com/mdo" class="text-white">@Moses</a>.
      </p>
    </footer>
  </div>
</body>

{% endblock content %}

accounts/templates/login.html
{% extends 'base.html' %}
<!-- load static tags -->
{% load static %}
<!-- css -->
{% block css %}
<style>
  .bd-placeholder-img {
    font-size: 1.125rem;
    text-anchor: middle;
    -webkit-user-select: none;
    -moz-user-select: none;
    user-select: none;
  }

  @media (min-width: 768px) {
    .bd-placeholder-img-lg {
      font-size: 3.5rem;
    }
  }
  html,
  body {
    height: 100%;
  }

  body {
    display: flex;
    align-items: center;
    padding-top: 40px;
    padding-bottom: 40px;
    background-color: #f5f5f5;
  }

  .form-signin {
    width: 100%;
    max-width: 330px;
    padding: 15px;
    margin: auto;
  }

  .form-signin .checkbox {
    font-weight: 400;
  }

  .form-signin .form-floating:focus-within {
    z-index: 2;
  }

  .form-signin input[type="email"] {
    margin-bottom: -1px;
    border-bottom-right-radius: 0;
    border-bottom-left-radius: 0;
  }

  .form-signin input[type="password"] {
    margin-bottom: 10px;
    border-top-left-radius: 0;
    border-top-right-radius: 0;
  }
</style>
{% endblock css %}

<!-- title -->
{% block title %} {{page_title}} {% endblock title %}

<!-- content begins -->
{% block content %}
<body class="text-center">
  <main class="form-signin">
    <form method="POST">
      {% csrf_token %}
      <img
        class="mb-4"
        src="{% static 'images/logos.png' %}"
        alt=""
        width="72"
        height="57"
      />
      <h1 class="h3 mb-3 fw-normal">Login</h1>

      {% if err %}
      <p class="mb-3 fw-normal text-danger">{{err}}</p>
      {% endif %}

      <div class="form-floating mb-2">
        <input
          type="text"
          name="username"
          id="username"
          class="form-control"
          placeholder="username"
        />

        <label for="username">Username</label>
      </div>

      <input type="submit" value="Login" class="w-100 btn btn-lg btn-primary" />
      <p class="mt-5 mb-3 text-muted">&copy; 2022</p>
    </form>
  </main>
</body>
{% endblock content %}

accounts/templates/mfa_auth_base.html
{% extends "base.html" %}

accounts/templates/register.html
{% extends 'base.html' %}
<!-- title -->

{% block title %} {{page_title}} {% endblock title %}

<!-- load static tags -->
{% load static %}
<!-- css -->
{% block css %}
<style>
  .bd-placeholder-img {
    font-size: 1.125rem;
    text-anchor: middle;
    -webkit-user-select: none;
    -moz-user-select: none;
    user-select: none;
  }

  @media (min-width: 768px) {
    .bd-placeholder-img-lg {
      font-size: 3.5rem;
    }
  }
  html,
  body {
    height: 100%;
  }

  body {
    display: flex;
    align-items: center;
    padding-top: 40px;
    padding-bottom: 40px;
    background-color: #f5f5f5;
  }

  .form-signin {
    width: 100%;
    max-width: 330px;
    padding: 15px;
    margin: auto;
  }

  .form-signin .checkbox {
    font-weight: 400;
  }

  .form-signin .form-floating:focus-within {
    z-index: 2;
  }

  .form-signin input[type="email"] {
    margin-bottom: -1px;
    border-bottom-right-radius: 0;
    border-bottom-left-radius: 0;
  }

  .form-signin input[type="password"] {
    margin-bottom: 10px;
    border-top-left-radius: 0;
    border-top-right-radius: 0;
  }
</style>
{% endblock css %}
<!-- content begins -->
{% block content %}
<body class="text-center">
  <main class="form-signin">
    <form method="POST">
      {% csrf_token %}
      <img
        class="mb-4"
        src="{% static 'images/logos.png' %}"
        alt=""
        width="72"
        height="57"
      />
      <h1 class="h3 mb-3 fw-normal">Register</h1>

      {% if error %}
      <p class="mb-3 fw-normal text-danger">{{error}}</p>
      {% endif %}

      <div class="form-floating mb-2">
        <input
          type="text"
          name="Surname"
          id="Surname"
          class="form-control"
          placeholder="Surname"
        />

        <label for="surname">Surname</label>

        <div class="form-floating mb-2">
          <input
            type="text"
            name="display-name"
            id="display-name"
            class="form-control"
            placeholder="display Name"
          />
  
          <label for="username">First Name</label>

          <div class="form-floating mb-2">
            <input
              type="text"
              name="Lastname"
              id="Lastname"
              class="form-control"
              placeholder="Lastname"
            />
    
            <label for="last_name">Last name</label>

            <div class="form-floating mb-2">
              <input
                type="email"
                name="email"
                id="email"
                class="form-control"
                placeholder="email"
              />
      
              <label for="email">Email</label>

      <div class="form-floating mb-2">
        <input
          type="text"
          name="username"
          id="username"
          class="form-control"
          placeholder="username"
        />

        <label for="username">Username</label>
      <input
        type="submit"
        value="Register"
        class="w-100 btn btn-lg btn-primary"
      />
      <p class="mt-5 mb-3 text-muted">&copy; 2022</p>
    </form>
  </main>
</body>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description" content="" />
    <meta name="author" content="John, Owolabi Idogun" />
    <meta name="generator" content="Hugo 0.82.0" />
    <title>web fingerprint with mfa | {% block title %} {% endblock title %}</title>

    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link
      href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap"
      rel="stylesheet"
    />

    <!-- Bootstrap core CSS -->
    <link
      href="{% static 'css/bootstrap/css/bootstrap.min.css' %}"
      rel="stylesheet"
    />

    <script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
    <!-- <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script> -->
    {% block head %} {% endblock %} {% block css %} {% endblock css %}
  </head>

  {% block content %} {% endblock content %}
</html>